[toolchain]
channel = "nightly-2024-06-20"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = d8a38b00024cd7156dea4ce8fd8ae113a2745e7f

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
