[toolchain]
channel = "nightly-2024-10-17"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 798fb83f7d24e31b16acca113496f39ff168c143

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
